[phases.build]
dependsOn = ["install"]

[phases.install]
cmds = [
  "find . -type d -name '__pycache__' -exec rm -rf {} + || true",
  "find . -type f -name '*.pyc' -delete || true",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python start.py"